version: '3'
services:
  dentistan:
    # Build kısmında "context" belirtmek bazen hayat kurtarır
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dentistan_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
