version: '3'
services:
  dentistan:
    image: dentistan:latest # (veya build: . yazÄ±yorsa kalsÄ±n)
    container_name: dentistan_app
    restart: always
    ports:
      - "3000:3000"
    # ðŸ‘‡ Ä°ÅžTE BU BÃ–LÃœM Ã‡OK Ã–NEMLÄ°, YOKSA EKLÄ°YORUZ ðŸ‘‡
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
      - GCS_PROJECT_ID=${GCS_PROJECT_ID}
      - GCS_CLIENT_EMAIL=${GCS_CLIENT_EMAIL}
      - GCS_PRIVATE_KEY=${GCS_PRIVATE_KEY}
