version: '3'
services:
  dentistan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dentistan_app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

    environment:
      - MONGODB_URI=${MONGODB_URI}
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
      - GCS_PROJECT_ID=${GCS_PROJECT_ID}
      - GCS_CLIENT_EMAIL=${GCS_CLIENT_EMAIL}
      - GCS_PRIVATE_KEY=${GCS_PRIVATE_KEY}
