version: '3'
services:
  dentistan:
    build: .
    container_name: dentistan_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
      - GCS_PROJECT_ID=${GCS_PROJECT_ID}
      - GCS_CLIENT_EMAIL=${GCS_CLIENT_EMAIL}
      - GCS_PRIVATE_KEY=${GCS_PRIVATE_KEY}
      - TURNSTILE_SECRET_KEY=${TURNSTILE_SECRET_KEY}
      - NEXT_PUBLIC_TURNSTILE_SITE_KEY=${NEXT_PUBLIC_TURNSTILE_SITE_KEY}
